export enum ActionType {


    GET_ALLGAMES=' GET_ALLGAMES',
    GET_ALLGAMES_SUCCESS="GET_ALLGAMES_SUCCESS",
    GET_ALLGAMES_FAIL="GET_ALLGAMES_FAIL",

    GET_ALLGAMESBYTIME=' GET_ALLGAMESBYTIME',
    GET_ALLGAMESBYTIME_SUCCESS="GET_ALLGAMESBYTIME_SUCCESS",
    GET_ALLGAMESBYTIME_FAIL="GET_ALLGAMESBYTIME_FAIL",


    GET_ALLGAMESBYPLAYERS=' GET_ALLGAMESBYPLAYERS',
    GET_ALLGAMESBYPLAYERS_SUCCESS="GET_ALLGAMESBYPLAYERS_SUCCESS",
    GET_ALLGAMESBYPLAYERS_FAIL="GET_ALLGAMESBYPLAYERS_FAIL"
}